# Generated by Django 3.2.5 on 2022-07-03 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('index', models.BigIntegerField(default=0)),
                ('import_id', models.CharField(max_length=255, null=True)),
                ('base_unit_content', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('base_unit_content_uom', models.CharField(max_length=255, null=True)),
                ('no_of_base_units', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('gtin', models.CharField(max_length=255, null=True)),
                ('kollex_product_id', models.CharField(max_length=255, null=True)),
                ('manufacturer', models.CharField(max_length=255, null=True)),
                ('manufacturer_gln', models.CharField(max_length=255, null=True)),
                ('manufacturer_id', models.CharField(max_length=255, null=True)),
                ('flags', models.CharField(max_length=255, null=True)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('refund_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gfgh_product_id', models.CharField(max_length=255, null=True)),
                ('sales_unit_pkgg', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('active', models.BigIntegerField(default=0)),
            ],
        ),
    ]
